language: python
jobs:
   include:
      - name: "Python 3.7.0 on Xenial Linux"
        python: 3.7           # this works for Linux but is ignored on macOS or Windows
        before_install:
         - sudo apt-get -y install libopus0 libopusfile0 libvorbisfile3
      - name: "Python 3.7 on macOS"
        os: osx
        osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
        language: shell       # 'language: python' is an error on Travis CI macOS
      - name: "Python 3.8.0 on Windows"
        os: windows           # Windows 10.0.17134 N/A Build 17134
        language: shell       # 'language: python' is an error on Travis CI Windows
        before_install:
         - choco install python --version 3.8.0
         - python -m pip install --upgrade pip
        env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
   - pip3 install numpy       # All three OSes agree about 'pip3'
   - pip3 install pytest
   - pip3 install .
script:
   - cd tests
   - pytest -v
